import { NewsAPI } from "../types/types";

export const NEWS_API: NewsAPI = {
  baseUrl: "https://newsapi.org/v2",
  apiKey: "a832e6c5806745be8e709544ba3b9430",
};
export const NYC_API: NewsAPI = {
  baseUrl: "https://api.nytimes.com/svc/search/v2",
  apiKey: "uo5B7nCXLVmgcjYLBdNABIqc4P16PHlR",
};
export const G_API: NewsAPI = {
  baseUrl: "https://content.guardianapis.com",
  apiKey: "14b9e1d2-3233-4952-900f-d11829a94314",
};

// news-api globals
//everything route
export const S1_PARAMS = {
  searchIn: ["title", "description", "content"],
  language: [
    "ar",
    "de",
    "en",
    "es",
    "fr",
    "he",
    "it",
    "nl",
    "no",
    "pt",
    "ru",
    "sv",
    "ud",
    "zh",
  ],
  sortBy: ["relevancy", "popularity", "publishedAt"],
  category: [
    "business",
    "entertainment",
    "general",
    "health",
    "science",
    "sports",
    "technology",
  ],
  coutry: [
    "ae",
    "ar",
    "at",
    "au",
    "be",
    "bg",
    "br",
    "ca",
    "ch",
    "cn",
    "co",
    "cu",
    "cz",
    "de",
    "eg",
    "fr",
    "gb",
    "gr",
    "hk",
    "hu",
    "id",
    "ie",
    "il",
    "in",
    "it",
    "jp",
    "kr",
    "lt",
    "lv",
    "ma",
    "mx",
    "my",
    "ng",
    "nl",
    "no",
    "nz",
    "ph",
    "pl",
    "pt",
    "ro",
    "rs",
    "ru",
    "sa",
    "se",
    "sg",
    "si",
    "sk",
    "th",
    "tr",
    "tw",
    "ua",
    "us",
    "ve",
    "za",
  ],
};
